version: "3.7"
services:

  #Php app
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: todo-example
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    links:
      - db
    networks:
      - mynetwork
  #Nginx
  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d/
    links:
      - app
    networks:
      - mynetwork 
  db:
    image: postgres:14.2
    ports:
      - "5432:5432"
   # volumes:
    #  - ./todo-database/data:/var/lib/postgresql/data:rw
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
